### ISSUE TITLE
Implement Home page

### ISSUE THREAD

**Issue by aurelticot** [verida/verida-one-webapp#217]
As of creation of this ticket, the web app have a very minimal Home page saying "Coming Soon" as seen on the demo deployment: https://demo.verida.one

In a separate deployment (with WebFlow), we have a landing page at https://www.verida.one for marketing purpose.
Ultimately, the web app will be hosted on ww.verida.one and the WebFlow landing page will be decommissioned. Meaning the web app must have a (useful) Home page.

For now, we can "basically" replicate what's the landing page as a Home page.

Except maybe for the header and footer which components have already been implemented.

**Comment by icetrust0212** [comment]
https://github.com/verida/verida-one-webapp/pull/219
