### ISSUE TITLE
Implement Search feature

### ISSUE THREAD

**Issue by aurelticot** [verida/verida-one-webapp#9]
A rough idea of the implementation is as follow:

- A dedicated molecule component for the Search field
- A dedicated molecule for the Search result item
- A dedicated organism component for the Search Result
- I'd say the Header integrates these component and manages the state but depending on the complexity it might good to move into a hook and dedicated components
- The Search Result component will have to be positioned below the Search Field and accomodate the different designs on large and narrow screens. We'll have to look whether a `position: fixed` is enough or if a portal is needed.
- The query being async, we should look at using `useQuery`
- A debounce of the search query is likely needed
- A loading state will be needed as well as an error state. If no design available, ask the design team
- Clicking on a search result item will redirect to the profile page and clear the state of the search

**Comment by nick-verida** [comment]
Just DID-based search. Exact match on a DID as per account explorer
